begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select no_plan();
select has_column('public', 'places', 'place_type', 'DB-C30: preserves the current place classification');
select has_column('public', 'cool_spots', 'setting', 'DB-C30: stores setting');
select has_column('public', 'cool_spots', 'cooling_features', 'DB-C30: stores cooling_features');
select has_column('public', 'cool_spots', 'cooling_details', 'DB-C30: stores cooling_details');
select has_column('public', 'cool_spots', 'area_description', 'DB-C30: stores area_description');
select has_column('public', 'cool_spots', 'cost', 'DB-C30: stores cost');
select has_column('public', 'cool_spots', 'eligibility', 'DB-C30: stores eligibility');
select has_column('public', 'cool_spots', 'seating', 'DB-C30: stores seating');
select has_column('public', 'cool_spots', 'drinking_water', 'DB-C30: stores drinking_water');
select has_column('public', 'cool_spots', 'toilets', 'DB-C30: stores toilets');
select has_column('public', 'cool_spots', 'wheelchair_access', 'DB-C30: stores wheelchair_access');
select has_column('public', 'cool_spots', 'staffed_when_open', 'DB-C30: stores staffed_when_open');
select has_column('public', 'cool_spots', 'tables', 'DB-C30: stores tables');
select has_column('public', 'cool_spots', 'posted_stay_limit_status', 'DB-C30: stores posted_stay_limit_status');
select has_column('public', 'cool_spots', 'posted_stay_limit_minutes', 'DB-C30: stores posted_stay_limit_minutes');
select has_column('public', 'cool_spots', 'additional_information', 'DB-C30: stores additional_information');
select has_column('public', 'cool_spots', 'hours_text', 'DB-C30: stores hours_text');
select has_column('public', 'cool_spots', 'hours_time_zone', 'DB-C30: stores hours_time_zone');
select hasnt_column('public', 'places', 'location_scope', 'does not introduce the rejected location scope');
select hasnt_column('public', 'cool_spots', 'eligibility_details', 'does not introduce eligibility details');
select exists(select 1 from information_schema.columns where table_schema='public' and table_name='cool_spots' and column_name='hours_time_zone') as ready \gset
\if :ready
insert into places(id,name,location) values ('00000000-0000-4000-8000-000000000401','Cooling Test','SRID=4326;POINT(0 51)');
insert into cool_spots(id,place_id) values ('db-cooling-content','00000000-0000-4000-8000-000000000401');
select results_eq($$select setting,cost,eligibility,seating,drinking_water,toilets,wheelchair_access,staffed_when_open,tables,posted_stay_limit_status from cool_spots where id='db-cooling-content'$$,
 $$values ('unknown'::text,'unknown'::text,'unknown'::text,'unknown'::text,'unknown'::text,'unknown'::text,'unknown'::text,'unknown'::text,'unknown'::text,'unknown'::text)$$, 'missing facts stay unknown rather than becoming no/free/everyone');
select ok((select cooling_features='{}'::text[] and cooling_details is null and area_description is null and additional_information is null and posted_stay_limit_minutes is null and hours_text is null and hours_time_zone is null from cool_spots where id='db-cooling-content'), 'optional information remains absent');
select lives_ok($$update cool_spots set setting='indoors' where id='db-cooling-content'$$, 'DB-C31: accepts setting indoors');
select lives_ok($$update cool_spots set setting='outdoors' where id='db-cooling-content'$$, 'DB-C31: accepts setting outdoors');
select lives_ok($$update cool_spots set setting='both' where id='db-cooling-content'$$, 'DB-C31: accepts setting both');
select lives_ok($$update cool_spots set setting='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts setting unknown');
select throws_ok($$update cool_spots set setting='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid setting');
select throws_ok($$update cool_spots set setting=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for setting');
select lives_ok($$update cool_spots set cost='free' where id='db-cooling-content'$$, 'DB-C31: accepts cost free');
select lives_ok($$update cool_spots set cost='purchase_required' where id='db-cooling-content'$$, 'DB-C31: accepts cost purchase_required');
select lives_ok($$update cool_spots set cost='entry_fee' where id='db-cooling-content'$$, 'DB-C31: accepts cost entry_fee');
select lives_ok($$update cool_spots set cost='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts cost unknown');
select throws_ok($$update cool_spots set cost='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid cost');
select throws_ok($$update cool_spots set cost=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for cost');
select lives_ok($$update cool_spots set eligibility='everyone' where id='db-cooling-content'$$, 'DB-C31: accepts eligibility everyone');
select lives_ok($$update cool_spots set eligibility='limited' where id='db-cooling-content'$$, 'DB-C31: accepts eligibility limited');
select lives_ok($$update cool_spots set eligibility='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts eligibility unknown');
select throws_ok($$update cool_spots set eligibility='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid eligibility');
select throws_ok($$update cool_spots set eligibility=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for eligibility');
select lives_ok($$update cool_spots set seating='yes' where id='db-cooling-content'$$, 'DB-C31: accepts seating yes');
select lives_ok($$update cool_spots set seating='limited' where id='db-cooling-content'$$, 'DB-C31: accepts seating limited');
select lives_ok($$update cool_spots set seating='no' where id='db-cooling-content'$$, 'DB-C31: accepts seating no');
select lives_ok($$update cool_spots set seating='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts seating unknown');
select throws_ok($$update cool_spots set seating='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid seating');
select throws_ok($$update cool_spots set seating=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for seating');
select lives_ok($$update cool_spots set toilets='on_site' where id='db-cooling-content'$$, 'DB-C31: accepts toilets on_site');
select lives_ok($$update cool_spots set toilets='nearby' where id='db-cooling-content'$$, 'DB-C31: accepts toilets nearby');
select lives_ok($$update cool_spots set toilets='not_on_site' where id='db-cooling-content'$$, 'DB-C31: accepts toilets not_on_site');
select lives_ok($$update cool_spots set toilets='none' where id='db-cooling-content'$$, 'DB-C31: accepts toilets none');
select lives_ok($$update cool_spots set toilets='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts toilets unknown');
select throws_ok($$update cool_spots set toilets='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid toilets');
select throws_ok($$update cool_spots set toilets=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for toilets');
select lives_ok($$update cool_spots set drinking_water='yes' where id='db-cooling-content'$$, 'DB-C31: accepts drinking_water yes');
select lives_ok($$update cool_spots set drinking_water='no' where id='db-cooling-content'$$, 'DB-C31: accepts drinking_water no');
select lives_ok($$update cool_spots set drinking_water='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts drinking_water unknown');
select throws_ok($$update cool_spots set drinking_water='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid drinking_water');
select throws_ok($$update cool_spots set drinking_water=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for drinking_water');
select lives_ok($$update cool_spots set wheelchair_access='yes' where id='db-cooling-content'$$, 'DB-C31: accepts wheelchair_access yes');
select lives_ok($$update cool_spots set wheelchair_access='no' where id='db-cooling-content'$$, 'DB-C31: accepts wheelchair_access no');
select lives_ok($$update cool_spots set wheelchair_access='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts wheelchair_access unknown');
select throws_ok($$update cool_spots set wheelchair_access='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid wheelchair_access');
select throws_ok($$update cool_spots set wheelchair_access=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for wheelchair_access');
select lives_ok($$update cool_spots set staffed_when_open='yes' where id='db-cooling-content'$$, 'DB-C31: accepts staffed_when_open yes');
select lives_ok($$update cool_spots set staffed_when_open='no' where id='db-cooling-content'$$, 'DB-C31: accepts staffed_when_open no');
select lives_ok($$update cool_spots set staffed_when_open='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts staffed_when_open unknown');
select throws_ok($$update cool_spots set staffed_when_open='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid staffed_when_open');
select throws_ok($$update cool_spots set staffed_when_open=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for staffed_when_open');
select lives_ok($$update cool_spots set tables='yes' where id='db-cooling-content'$$, 'DB-C31: accepts tables yes');
select lives_ok($$update cool_spots set tables='no' where id='db-cooling-content'$$, 'DB-C31: accepts tables no');
select lives_ok($$update cool_spots set tables='unknown' where id='db-cooling-content'$$, 'DB-C31: accepts tables unknown');
select throws_ok($$update cool_spots set tables='future-invalid-code' where id='db-cooling-content'$$, '23514', null, 'rejects invalid tables');
select throws_ok($$update cool_spots set tables=null where id='db-cooling-content'$$, '23502', null, 'requires an explicit unknown for tables');
select lives_ok($$update places set place_type='library' where id='00000000-0000-4000-8000-000000000401'$$,'stores a library classification');
select throws_ok($$update places set place_type='invented' where id='00000000-0000-4000-8000-000000000401'$$,'23514',null,'rejects an unsupported classification');
select lives_ok($$update cool_spots set cooling_features=array['air_conditioning','fans','natural_ventilation','tree_shade','structural_shade','cooler_indoors','water_nearby'] where id='db-cooling-content'$$,'stores all seven current feature codes');
select throws_ok($$update cool_spots set cooling_features=array['drinking_water'] where id='db-cooling-content'$$,'23514',null,'drinking water stays a separate access fact');
select throws_ok($$update cool_spots set cooling_features=array['fans',null] where id='db-cooling-content'$$,'23514',null,'rejects a null feature');
select throws_ok($$update cool_spots set cooling_features=array[['fans','tree_shade']] where id='db-cooling-content'$$,'23514',null,'rejects a nested feature list');
select lives_ok($$update cool_spots set cooling_details=E'  四樓 reading room\n' where id='db-cooling-content'$$,'DB-C32: preserves meaningful cooling_details');
select is((select cooling_details from cool_spots where id='db-cooling-content'), E'  四樓 reading room\n', 'reads original cooling_details');
select throws_ok($$update cool_spots set cooling_details='' where id='db-cooling-content'$$,'23514',null,'rejects blank cooling_details');
select throws_ok($$update cool_spots set cooling_details=U&'\0020\0009\3000' where id='db-cooling-content'$$,'23514',null,'rejects blank cooling_details');
select lives_ok($$update cool_spots set cooling_details=null where id='db-cooling-content'$$,'allows clearing optional cooling_details');
select lives_ok($$update cool_spots set area_description=E'  四樓 reading room\n' where id='db-cooling-content'$$,'DB-C32: preserves meaningful area_description');
select is((select area_description from cool_spots where id='db-cooling-content'), E'  四樓 reading room\n', 'reads original area_description');
select throws_ok($$update cool_spots set area_description='' where id='db-cooling-content'$$,'23514',null,'rejects blank area_description');
select throws_ok($$update cool_spots set area_description=U&'\0020\0009\3000' where id='db-cooling-content'$$,'23514',null,'rejects blank area_description');
select lives_ok($$update cool_spots set area_description=null where id='db-cooling-content'$$,'allows clearing optional area_description');
select lives_ok($$update cool_spots set additional_information=E'  四樓 reading room\n' where id='db-cooling-content'$$,'DB-C32: preserves meaningful additional_information');
select is((select additional_information from cool_spots where id='db-cooling-content'), E'  四樓 reading room\n', 'reads original additional_information');
select throws_ok($$update cool_spots set additional_information='' where id='db-cooling-content'$$,'23514',null,'rejects blank additional_information');
select throws_ok($$update cool_spots set additional_information=U&'\0020\0009\3000' where id='db-cooling-content'$$,'23514',null,'rejects blank additional_information');
select lives_ok($$update cool_spots set additional_information=null where id='db-cooling-content'$$,'allows clearing optional additional_information');
select lives_ok($$update cool_spots set posted_stay_limit_status='limited',posted_stay_limit_minutes=30 where id='db-cooling-content'$$,'DB-C33: limited with 30 minutes');
select throws_ok($$update cool_spots set posted_stay_limit_status='limited',posted_stay_limit_minutes=null where id='db-cooling-content'$$,'23514',null,'DB-C33: limited with null minutes');
select throws_ok($$update cool_spots set posted_stay_limit_status='limited',posted_stay_limit_minutes=0 where id='db-cooling-content'$$,'23514',null,'DB-C33: limited with 0 minutes');
select throws_ok($$update cool_spots set posted_stay_limit_status='limited',posted_stay_limit_minutes=-1 where id='db-cooling-content'$$,'23514',null,'DB-C33: limited with -1 minutes');
select lives_ok($$update cool_spots set posted_stay_limit_status='unknown',posted_stay_limit_minutes=null where id='db-cooling-content'$$,'DB-C33: unknown with null minutes');
select lives_ok($$update cool_spots set posted_stay_limit_status='no_stated_limit',posted_stay_limit_minutes=null where id='db-cooling-content'$$,'DB-C33: no_stated_limit with null minutes');
select throws_ok($$update cool_spots set posted_stay_limit_status='unknown',posted_stay_limit_minutes=30 where id='db-cooling-content'$$,'23514',null,'DB-C33: unknown with 30 minutes');
select throws_ok($$update cool_spots set posted_stay_limit_status='no_stated_limit',posted_stay_limit_minutes=30 where id='db-cooling-content'$$,'23514',null,'DB-C33: no_stated_limit with 30 minutes');
select throws_ok($$update cool_spots set posted_stay_limit_status='invalid',posted_stay_limit_minutes=null where id='db-cooling-content'$$,'23514',null,'DB-C33: invalid with null minutes');
select throws_ok($$update cool_spots set hours_text='Monday 9-5' where id='db-cooling-content'$$,'23514',null,'requires a time zone alongside hours');
select lives_ok($$update cool_spots set hours_text='Monday 9-5',hours_time_zone='Europe/London' where id='db-cooling-content'$$,'preserves supplied hours without inferring open now');
select throws_ok($$update cool_spots set hours_time_zone='' where id='db-cooling-content'$$,'23514',null,'rejects an empty hours time zone');
select lives_ok($$update cool_spots set hours_text=null,hours_time_zone=null where id='db-cooling-content'$$,'allows unknown hours');
select ok((select place_id='00000000-0000-4000-8000-000000000401' from cool_spots where id='db-cooling-content'),'content updates preserve both identities');
\else
select skip('behavior requires the new cooling-content columns');
\endif
select * from finish();
rollback;
